### PR TITLE
Refactor native exception handling

### PR DESCRIPTION
**Pull request by mscheibler**
I am currently working to add BCM support to the JavaCAN lib and stumbled across a problem with the native exception handling. It seems like the Java VM interferes with the Linux errno.

When a system call fails and errno is set, it is only preserved as long as there is no JNI function or Java code is called. This leads to the problem that the OSError class is unable to retrieve the actual errno. In my case i always got 2 "No such file or directory", which was misleading. It took me a few hours to realize that is was on the wrong track.

So i took the liberty to refactor the native exception handling to be done in the native C part to circumvent this issue.

Maybe it is a good idea to remove the OSError class at all, as it now serves only as value holder. This could also be done by the LinuxNativeOperationException. This would reduce the C code for throwing the exception. What do you think?

### CODE REVIEW

**Comment by pschichtel** [comment]
Let's move the discussion here. I'll have a look at this later today. I'm generally open to merging the OSError into the exception, I think they are 1:1 anyway.

**Comment by pschichtel** [comment]
So as suspected: The tests work fine for me (just pulled the tests without anything else). So there must be something system specific to it. Can you share your combination of Distro and Java? Really interested in why this works for me, but not for you.

Also: It would be great of you could setup your IDE to use 4 spaces for indention instead of tabs, that how the rest of the code base is.

I've pulled your branch and do a few changes to hit (including reformatting)

**Comment by mscheibler** [comment]
Sorry for the Tabs, i already changed it yesterday in the evening.

It is most interesting that this behavior changes between the systems. I am running: `Ubuntu 18.04.3 LTS`.
I on the Java side i tried `OpenJDK Runtime Environment (build 1.8.0_232-8u232-b09-0ubuntu1~18.04.1-b09)`
and `OpenJDK Runtime Environment (build 11.0.5+10-post-Ubuntu-0ubuntu1.118.04)`

The stacktrace is most fascinating. On `bind` the errno is changed, while on `close` it works as supposed.
```
tel.schich.javacan.linux.LinuxNativeOperationException: Unable to bind! - OSError{errorNumber=2, errorMessage='No such file or directory'}
	at tel.schich.javacan.RawCanChannelImpl.bind(RawCanChannelImpl.java:51)
	at tel.schich.javacan.LinuxNativeOperationExceptionTest.testInvalidFileDesciptorError(LinuxNativeOperationExceptionTest.java:43)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:675)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
... <tons of JUnit Stack frames ommited> ...
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)
	Suppressed: tel.schich.javacan.linux.LinuxNativeOperationException: Unable to close socket! - OSError{errorNumber=9, errorMessage='Bad file descriptor'}
		at tel.schich.javacan.AbstractCanChannel.implCloseSelectableChannel(AbstractCanChannel.java:91)
		at java.base/java.nio.channels.spi.AbstractSelectableChannel.implCloseChannel(AbstractSelectableChannel.java:242)
		at java.base/java.nio.channels.spi.AbstractInterruptibleChannel.close(AbstractInterruptibleChannel.java:112)
		at tel.schich.javacan.LinuxNativeOperationExceptionTest.testInvalidFileDesciptorError(LinuxNativeOperationExceptionTest.java:41)
		... 65 more
```

**Comment by pschichtel** [comment]
I guess a strace would show what the system tried to do in between, but I doubt we can do much about it anyway. I've started implementing a [small annotation processor](https://github.com/pschichtel/jni-access-generator) that generates the c code to throw exceptions and create objects. Given that the situations that trigger these calls are not typically on a hot path I'd say performance wise it doesn't make a difference.

Ill refractor this on my branch to use the new functions once the generator is working.

**Comment by mscheibler** [comment]
Sounds good.
It would be nice if we could stabilize the API changes in this branch, so i can rebase my `add-BCM-support` onto it. I hope that this minimizes future merge efforts. The exception handling refactoring is just a side-quest :)

Nevertheless, I will run my test with strace this evening on the master before the refactoring to check what happens.

**Comment by mscheibler** [comment]
The `errno` gets modified because i started the Unit test from the IDE and the 1st classpath entry does not contain the OSError class.
```
16517      0.000062 bind(1036, {sa_family=AF_CAN, sa_data="\342\275\6\0\0\0\0\0\0\0\0\0\0\0"}, 16) = -1 EBADF (Bad file descriptor)
16517      0.000093 stat("/home/maik/prj/JavaCAN/target/test-classes/tel/schich/javacan/linux/OSError.class", 0x7fd2bde24080) = -1 ENOENT (No such file or directory)
16517      0.000036 stat("/home/maik/prj/JavaCAN/target/classes/tel/schich/javacan/linux/OSError.class", {st_mode=S_IFREG|0664, st_size=1557, ...}) = 0
16517      0.000112 openat(AT_FDCWD, "/home/maik/prj/JavaCAN/target/classes/tel/schich/javacan/linux/OSError.class", O_RDONLY) = 37
16517      0.000041 fstat(37, {st_mode=S_IFREG|0664, st_size=1557, ...}) = 0
```

Such things may happen any time. If you lookup the `errno` [man-page](http://man7.org/linux/man-pages/man3/errno.3.html) it is adviced to store the `errno` if you do not use it immediately:

> A common mistake is to do
>
>    if (somecall() == -1) {
>        printf("somecall() failed\n");
>        if (errno == ...) { ... }
>    }
>
> where errno no longer needs to have the value it had upon return from
> somecall() (i.e., it may have been changed by the printf(3)).

So i think it is a **huge** risk to get it by another call from the JVM, as we have absolutely no control of what may happen in between.

**Comment by pschichtel** [comment]
Yep, I assumed it must be related to Eclipse's test runner doing something funky. I tried to avoid this issue by always early-returning, when errno != 0 is detected, assuming that it would just move up the stack directly back into my Java code. I agree, this assumption is not guaranteed to hold true with javaagent, AOP and reflection stuff possibly going on.
The code generator I've been working on is mostly functional. I'm pretty sure I get this all done and merged by the end of this week.

**Comment by mscheibler** [comment]
Good to hear.
I have my first version of the BCM channel working. But i will have to refactor it because i learned a lot about padding in C structures yesterday. ;)

**Comment by pschichtel** [comment]
I'll merge this manually

**Pull request merged**
